name: ServiceLocator
options:
  developmentLanguage: en
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 12.0
    macOS: 10.14
    tvOS: 12.0
    watchOS: 6.0
  xcodeVersion: 15.0
settings:
  base:
    SWIFT_VERSION: "5.7"
    PRODUCT_BUNDLE_IDENTIFIER: com.nikitavasilev.capture-kit
    CODE_SIGN_STYLE: automatic
    GENERATE_INFOPLIST_FILE: YES
attributes:
  ORGANIZATIONNAME: space-code
schemes:
  ServiceLocator:
      build:
        targets:
          ServiceLocator: all
      run:
        config: Debug
      test:
        gatherCoverageData: true
        targets:
          - ServiceLocatorTests
        coverageTargets:
          - ServiceLocator
targets:
  ServiceLocator:
    type: framework
    supportedDestinations: [iOS, tvOS, macOS]
    sources:
      - path: ServiceLocator
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
        GENERATE_INFOPLIST_FILE: YES
        TARGETED_DEVICE_FAMILY: "1,2,3,4"
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
  ServiceLocatorTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, tvOS, macOS]
    sources:
      - ServiceLocatorTests
    dependencies:
      - target: ServiceLocator
    settings:
      base:
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
        GENERATE_INFOPLIST_FILE: YES
        TARGETED_DEVICE_FAMILY: "1,2,3,4"
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"